name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 5d1f7912a351f5d77ea3941ee6b33d48
          TIMEZONE: Asia/Seoul
